version: 2
updates:
  - package-ecosystem: cargo
    directory: /module-updater
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
